### ISSUE TITLE
normalmap not compiling against ImageMagick6

### ISSUE THREAD

**Issue by chris-blues** [eatdust/normalmap#1]
Continuation of the discussion held here: https://github.com/chris-blues/Nasa2FGearthview/issues/4#issuecomment-579902760
> Ok, I've added an issue button :)
> For the MagickCore issue, that is very weird, I did not touch that part of the code. The devel files of ImageMagic6 comes with a file named MagickCore.pc that is found by pkg-config. On my machine, it is there: /usr/lib64/pkgconfig/MagickCore.pc and should be found by the script.
> Could you check that this file is installed?

No such file on my system.

~~Lets move this discussion to your repo... [ done ]~~

**Comment by eatdust** [comment]
Ok, let's see on Debian, there?

/usr/lib/x86_64-linux-gnu/pkgconfig/MagickCore.pc
coming with/:
libmagickcore-6.q16-dev

If you have these really installed, I guess the binary waf script does something bad!

**Comment by chris-blues** [comment]
Ah, my bad!

I switched machines since I didn't want to hold up with my work machine to be swamped by the large textures. And I forgot to install the libmagickcore-6.q16-dev...

Works fine now! So the only new package required is pkg-config! This should be put into the readme I think.

Sorry for the noise...

**Comment by eatdust** [comment]
That's no noise, thanks for the debugging! (readme edited!)
